apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      name: eureka-service
      labels:
        app: eureka-service
    spec:
      hostname: eureka-service
      containers:
        - name: eureka-service
          image: eureka-service:2024
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka-service