apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      hostname: user-service
      containers:
        - name: user-service
          image: user-service:2024
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA_URL
              value: http://eureka-service:8761/eureka
            - name: DB_URL
              value: mysql://mysql:3306
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 0.2
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: user-service